#!/data/data/com.termux/files/usr/bin/bash -e

cd $HOME

unset LD_PRELOAD

cmdline="proot \
        --link2symlink \
        -0 \
        -r parrot-arm64 \
        -b /dev \
        -b /proc \
        -b /sdcard \
        -b parrot-arm64/root:/dev/shm \
        -w /root \
           /usr/bin/env -i \
           HOME=/root \
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \
           TERM=$TERM \
           LANG=C.UTF-8 \
           /bin/bash --login"

cmd="$@"
if [ "$#" == "0" ];then
    exec $cmdline
else
    $cmdline -c "$cmd"
fi
